#include "poselink/transport/Protocol.h"
#include <cmath>
#include <cstring>
namespace poselink {
namespace { void U32(uint8_t* p,uint32_t v){ p[0]=uint8_t(v>>24);p[1]=uint8_t(v>>16);p[2]=uint8_t(v>>8);p[3]=uint8_t(v); } uint32_t R32(const uint8_t* p){return (uint32_t(p[0])<<24)|(uint32_t(p[1])<<16)|(uint32_t(p[2])<<8)|p[3];} void U64(uint8_t* p,uint64_t v){for(int i=7;i>=0;--i){p[i]=uint8_t(v);v>>=8;}} uint64_t R64(const uint8_t* p){uint64_t v=0;for(int i=0;i<8;++i)v=(v<<8)|p[i];return v;} void F32(uint8_t* p,double value){uint32_t bits;float f=float(value);std::memcpy(&bits,&f,4);U32(p,bits);} double RF32(const uint8_t* p){uint32_t bits=R32(p);float f;std::memcpy(&f,&bits,4);return f;} }
bool IsFiniteAndNormalized(const PoseSample& p){ const auto& q=p.orientation; double n=q.x*q.x+q.y*q.y+q.z*q.z+q.w*q.w; return std::isfinite(p.position.x)&&std::isfinite(p.position.y)&&std::isfinite(p.position.z)&&std::isfinite(q.x)&&std::isfinite(q.y)&&std::isfinite(q.z)&&std::isfinite(q.w)&&n>0.98&&n<1.02; }
std::array<uint8_t,kPosePacketSize> EncodePose(uint32_t seq,const PoseSample& p){ std::array<uint8_t,kPosePacketSize> b{}; U32(b.data(),kProtocolMagic);b[4]=kProtocolVersion;b[5]=1;b[6]=p.valid?1:0;U32(b.data()+8,seq);U64(b.data()+12,p.timestampUs);U32(b.data()+20,p.objectId);F32(b.data()+24,p.position.x);F32(b.data()+28,p.position.y);F32(b.data()+32,p.position.z);F32(b.data()+36,p.orientation.x);F32(b.data()+40,p.orientation.y);F32(b.data()+44,p.orientation.z);F32(b.data()+48,p.orientation.w);return b; }
bool DecodePose(const uint8_t* b,size_t n,DecodedPacket& o,std::string& e){ if(n!=kPosePacketSize){e="unexpected packet size";return false;} if(R32(b)!=kProtocolMagic){e="bad magic";return false;} if(b[4]!=kProtocolVersion||b[5]!=1){e="unsupported protocol or message";return false;} o.sequence=R32(b+8);o.pose.timestampUs=R64(b+12);o.pose.objectId=R32(b+20);o.pose.valid=b[6]==1;o.pose.position={RF32(b+24),RF32(b+28),RF32(b+32)};o.pose.orientation={RF32(b+36),RF32(b+40),RF32(b+44),RF32(b+48)};if(!IsFiniteAndNormalized(o.pose)){e="non-finite or non-normalized pose";return false;}return true; }
}
